import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'example'}],
  hardwareSidebar:[{type: 'autogenerated', dirName: 'hardware'}],
  softwareSidebar:[{type: 'autogenerated', dirName: 'software'}],

  // specSidebar:[{type: 'autogenerated', dirName: 'spec'}],
  specSidebar: [
    'spec/intro',
    'spec/get_started',
    {
      type: 'category',
      label: 'Guides',
      link:{type: 'doc', id:'spec/guides'},
      items: [
        'spec/guides/custom_extension',
        'spec/guides/rules',
      ],
    },
    {
      type: 'html',
      value:
        '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 0.25rem 1rem;" />',
    },
    {
      type:'category',
      label:'The ISA Specification',
      link: {type: 'doc', id: 'spec/isa'},
      items:[
        {
          type:"link",
          label:"ISA Volume 1: Priv",
          href:"pathname:///docs/reference/isa/unpriv/intro.html",
        },
        {
          type:"link",
          label:"ISA Volume 2: Un-Priv",
          href:"pathname:///docs/reference/isa/priv/priv-intro.html",
        },

      ],
    },
    {
      type:'category',
      label:'Profiles',
      link: {type: 'doc', id: 'spec/profiles'},
      items:[
        {
          type:"doc",
          label:"RVA23",
          id:"spec/profiles/rva23",
        },
        {
          type:"doc",
          label:"RVB23",
          id:"spec/profiles/rvb23",
        },
        {
          type:"doc",
          label:"RISC-V Profiles",
          id:"spec/profiles/riscv-profiles",
        },

      ],
    },
    {
      type:'category', 
      label: 'Non-ISA',
      collapsed:true,
      link: {type: 'doc', id:'spec/non-isa'},
      items:[
        {
          type:'category',
          label:'Processor Infrastructure',
          collapsed:true,
          items:[
            'spec/non-isa/advanced-interrupt',
            'spec/non-isa/iommu-architecture',
            'spec/non-isa/platform-interrupt',
            'spec/non-isa/server-soc',
          ],
        },
        {
          type:'category',
          label:'Debug, Trace & RAS',
          collapsed:true,
          items:[
            'spec/non-isa/debug',
            'spec/non-isa/efficient-trace',
            'spec/non-isa/n-trace',
            'spec/non-isa/qos',
            'spec/non-isa/reri',
            'spec/non-isa/trace-conectors',
            'spec/non-isa/trace-control-interface',
            'spec/non-isa/unformatted-trace',
          ],
        },
        {
          type:'category',
          label:'Platform Software',
          collapsed:true,
          items:[
            'spec/non-isa/functional-fixed',
            'spec/non-isa/semihosting',
            'spec/non-isa/sbi',
            'spec/non-isa/uefi',
            'spec/non-isa/io-mapping',
          ],
        },
        {
          type:'category',
          label:'Application Software',
          collapsed:true,
          items:[
            'spec/non-isa/abi',
          ],
        },
        // {
        //   type:'category',
        //   label:'Glossary'
        //   collapsed:true,
        //   items:[
        //     Terms,
        //     Acronyms,
        //     extensions-list,
        //     csr,
        //   ],
        // },
      ],
      
    },
    // {
    //   type:'category',
    //   label:'Non-ISA Specifications',
    //   link: {type: 'doc', id: 'spec/non-isa'},
    //   items:[
    //     {
    //       type:'autogenerated', dirName: 'spec/non-isa'
    //     }
    //   ],
    // },
  ],

};

export default sidebars;
